# Generated by Django 2.0.7 on 2020-09-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='owner',
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
