# Generated by Django 2.0.7 on 2020-09-05 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_serviceprovider_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='cordinate',
        ),
    ]
