# Generated by Django 2.0.7 on 2020-09-05 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0005_auto_20200905_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='serviceProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(max_length=9)),
                ('lon', models.FloatField(max_length=9)),
                ('services', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('other', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
