# Generated by Django 2.0.7 on 2020-09-06 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20200905_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceprovider',
            old_name='owner',
            new_name='name',
        ),
    ]
