# Generated by Django 2.0.7 on 2020-10-29 06:16

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20200906_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.upload_path),
        ),
    ]
