# Generated by Django 2.0.7 on 2020-09-04 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(max_length=9)),
                ('lon', models.FloatField(max_length=9)),
                ('cordinate', models.CharField(editable=False, max_length=100)),
                ('neighbours', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('name', models.CharField(max_length=70)),
                ('need', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProvider_Motor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(max_length=9)),
                ('lon', models.FloatField(max_length=9)),
                ('cordinate', models.CharField(editable=False, max_length=100)),
                ('name', models.CharField(max_length=70)),
                ('services', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('other', models.CharField(max_length=100)),
            ],
        ),
    ]
